### PR TITLE
Custom Breakpoints + xs Col breakpoint + Respect padding config in ContainerFluid

### PR DESCRIPTION
**Pull request by damassi**
Adds the ability to customize breakpoints via the ThemeProvider, and added `xs` to `<Col>`. And additionally, noticed that when I adjusted container settings in `gridTheme` nothing would update, and noticed that `ContainerFluid` wasn't picking up the setting.

### CODE REVIEW

**Comment by peterlazzarino** [comment]
@damassi seems part of this might have been addressed in a new version #14

**Comment by peterlazzarino** [comment]
ah actually thats a bit older than I thought and the current version's Container component doesnt seem to take theme props for the grid.

**Comment by dragma** [comment]
Awesome.
Could you just update the documentation ? And I'll merge this !

**Comment by damassi** [comment]
@dragma - I've been on vacation but just getting back; I'll update this over the weekend. Thanks!

**Comment by damassi** [comment]
@dragma - looking at my changed files I realized I did update the docs. Did you need something else?

**Comment by dragma** [comment]
I merge the pull request now. I'll only be able to update npm tomorrow.
Thanks a lot

**Comment by dragma** [comment]
Package [version 1.0.4](https://www.npmjs.com/package/styled-bootstrap-grid) is now published !

**Comment by damassi** [comment]
Thanks @dragma 👍

**Comment by AWR14** [comment]
I want to add a custom breakpoint to the config e.g

`const GridTheme = {
  breakpoints: { // defaults below
    xxl: 1400,
    xl: 1200,
    lg: 992,
    md: 768,
    sm: 576,
    xs: 575,
  },
  row: {
    padding: 10, // default 15
  },
  col: {
    padding: 5, // default 15
  },
  container: {
    padding: 0, // default 15
    maxWidth: { // defaults below
      xxl: 1340,
      xl: 1140,
      lg: 960,
      md: 720,
      sm: 540,
      xs: 540,
    },
  },
};`

see the 'xxl', this doesn't seem to work. Is it currently possible>?

**Comment by dragma** [comment]
Nope I'm sorry.But maybe this is something we can work on.Le 25 mars 2019 16:56, AWR14 <notifications@github.com> a écrit :I want to add a custom breakpoint to the config e.g
const GridTheme = { breakpoints: { // defaults below xxl: 1400, xl: 1200, lg: 992, md: 768, sm: 576, xs: 575, }, row: { padding: 10, // default 15 }, col: { padding: 5, // default 15 }, container: { padding: 0, // default 15 maxWidth: { // defaults below xxl: 1340, xl: 1140, lg: 960, md: 720, sm: 540, xs: 540, }, }, };
see the 'xxl', this doesn't seem to work. Is it currently possible>?

**Comment by AWR14** [comment]
@dragma thats a shame, looking at the files on this PR it looks like all values are hard coded for the breakpoints. Do you think its something simple to do to add this functionality? 

guess we need to pass the gridtheme object and iterate over it and generate all the width, offsets, alignment classes for each breakpoint.

If you can point me in the right direction a little i could have a go at this

**Comment by dragma** [comment]
The default breakpoint values are hardcoded, but you can setup your own values for sm to xl.What you can't do is add custom breakpoint like "xxl".Le 25 mars 2019 17:23, AWR14 <notifications@github.com> a écrit :@dragma thats a shame, looking at the files on this PR it looks like all values are hard coded for the breakpoints. Do you think its something simple to do to add this functionality?
guess we need to pass the gridtheme object and iterate over it and generate all the width, offsets, alignment classes for each breakpoint.
If you can point me in the right direction a little i could have a go at this

**Pull request merged**
