### PR TITLE
Migrated project to typescript

### PR DESCRIPTION
**Pull request by hector-del-rio**
I've added types to the code base and done some major refactoring while doing so. The changes should all be backwards compatible, at least everything works with the projects I use it with.

Please let me know what you think of the proposed changes and feel free to comment if there's something that doesn't look quite right.

### CODE REVIEW

**Comment by dragma** [comment]
I guess I'll have to learn typescript now.:D
Amazing work. Thank you very much !

**Comment by dragma** [comment]
Hi @hector-del-rio ! 
I have an error trying to build the package.

I get the same error when I try `yarn build:types`. 
Since I'm a complete newbie with typescript, could you help me with this ?

**Comment by hector-del-rio** [comment]
Can you run `yarn run tsc --version` ? 

If you are using a global installation of typescript which is outdated, it won't work.

Perhaps package.json scripts should be changed to use the project local version of typescript

**Comment by hector-del-rio** [comment]
I just tested and realised that the issue comes when using yarn. 

Probably it installs some newer version of a package when running yarn install (it doesn't read package-lock.json).

if you use npm it will work, but perhaps we should open an issue to migrate to yarn and / or upgrade package versions.

**Comment by dragma** [comment]
@hector-del-rio 
I have the same issue with npm too.
`npm run build` triggers the same error.
npm version : 6.4.1
tsc version : 3.2.2

**Comment by hector-del-rio** [comment]
Revert package-lock.json and the run `npm install`. Then I guess it should work. 

If you remove the lock file, it will install again the latest matching versions. The same that happened when you used yarn

**Comment by dragma** [comment]
This should not bother, since the `package-lock.json` (or `yarn.lock`) is rebuild when I install the dependencies again. But of course, I have already tried to build the module with the original file.

Also, installing dependencies (with npm & yarn) in the example folder does not create any error, but once launched, the example does not work and triggers an error.
```
./src/index.js
Module not found: Can't resolve 'styled-bootstrap-grid' in '/home/florent/dev/styled-bootstrap-grid/example/src'
```

In the module's `package.json` file, I can see this
```
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
```

When I list the build files in the node_modules folder, it gives this (with yarn or npm): 
```
> ls -al node_modules/styled-bootstrap-grid/dist/
total 28
drwxr-xr-x 6 florent florent 4096 12 déc.  10:21 .
drwxr-xr-x 7 florent florent 4096 12 déc.  10:21 ..
drwxr-xr-x 2 florent florent 4096 12 déc.  10:21 aliases
drwxr-xr-x 7 florent florent 4096 12 déc.  10:21 components
-rw-r--r-- 1 florent florent  594 12 déc.  10:00 index.d.ts
drwxr-xr-x 2 florent florent 4096 12 déc.  10:21 media
drwxr-xr-x 2 florent florent 4096 12 déc.  10:21 utils
```
The `index.d.ts` file is here, but the `index.js` file is missing.

**Comment by hector-del-rio** [comment]
I run `cd examples/ && rm -rf yarn.lock && yarn`

Then:

```
 ✗ ls -als node_modules/styled-bootstrap-grid/dist
total 16
0 drwxr-xr-x   8 hdel  staff   256 Dec 12 10:46 .
0 drwxr-xr-x  20 hdel  staff   640 Dec 12 10:50 ..
0 drwxr-xr-x   8 hdel  staff   256 Dec 12 10:46 aliases
0 drwxr-xr-x   7 hdel  staff   224 Dec 12 10:46 components
8 -rw-r--r--   1 hdel  staff   594 Dec 12 10:46 index.d.ts
8 -rw-r--r--   1 hdel  staff  3620 Dec 12 10:46 index.js
0 drwxr-xr-x   8 hdel  staff   256 Dec 12 10:46 media
0 drwxr-xr-x   6 hdel  staff   192 Dec 12 10:46 utils
```

**Comment by dragma** [comment]
Can you remove the `styled-bootstrap-grid/dist` folder and try again ?
I guess I'll have to `npm run build` before doing anythig in `example/`.

**Comment by dragma** [comment]
Okay for no reason now it is working now. I havn't change anythig...

**Pull request merged**
