### PR TITLE
add feature: custom gridColumns, size xxl

### PR DESCRIPTION
**Pull request by imagine10255**
Hi, I re-submitted a new branch with feature changes and examples and documentation

add feature: 
1. custom gridColumns
2. size xxl (veryGiant)

### CODE REVIEW

**Comment by imagine10255** [comment]
Hi,Is there a problem with the code?

**Comment by dragma** [comment]
Hello !

Sorry for the delay. I'm testing your code right now, and it seems that the module breaks if we don't set the `ThemeProvider`. This `ThemeProvider` should be optionnal.

The error I get is this : TypeError: `Cannot read property 'getColGridColumns' of undefined`
Because of lines like this one : `p.theme.styledBootstrapGrid.getColGridColumns()`

I'm actually on vacation, but if you can't provide this tiny update during the weekend, I'll try to take time to do this next week.

Thanks a lot again for your work !

**Comment by dragma** [comment]
Nevermind, I've found some time to do this.
I also moved the gridColumns parameter from col, and placed i at the root level of the theme object.
Brace yourselves, v4 is comming !

**Comment by imagine10255** [comment]
Sorry to urge you, thank you for providing this package

**Pull request merged**
