### PR TITLE
Bumped version up to 2.0.0 as recommended in react docs.

### PR DESCRIPTION
**Pull request by hector-del-rio**
According to [react docs](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers):

> When you start using forwardRef in a component library, you should treat it as a breaking change and release a new major version of your library

I also found a very strange behaviour when using `React.forwardRef()` with styled-components `.attrs()`: props will be empty in component when doing this:

```
const StyledCol = styled(Col).attrs({
    xs: 12,
    sm: 6
})`...`

...

render() {
    return <StyledCol />;
}
```

but props will be ok when doing this:

```
const StyledCol = styled(Col)`...`

...

render() {
    return <StyledCol xs={12} sm={6} />;
}
```

### CODE REVIEW

**Comment by hector-del-rio** [comment]
After a lot of trial and error I found the solution for the later issue.

Changing this:

```
const MyCol = React.forwardRef((props, ref) => {...})

export default MyCol;
```

to this:


```
const MyCol = (props, ref) => {...}

export default React.forwardRef(MyCol);
```

did the trick and fixed the issue.

**Comment by dragma** [comment]
I'd like to implement latest bootstrap CSS (4.1.3) before pushing V2 in npm. I'll have some time to do this on Thursday ! 
If you want to do the typescript thing after that, be my guest! :P

**Comment by hector-del-rio** [comment]
@dragma do you still have the chance to work on this today?

**Comment by dragma** [comment]
I'm on it right now. I don't know if i'll have the time to complete it today, but i'll do my best ! :)

**Comment by hector-del-rio** [comment]
OK, no problem. Thank you for your effort.

**Comment by dragma** [comment]
Ok. I'm releasing right now just the tiny changes to bump boostrap version and launch v2.0 module. I'll push the new features after :)

**Pull request merged**
